//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add above に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string add2 {
            get {
                return ResourceManager.GetString("add2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add below に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string add3 {
            get {
                return ResourceManager.GetString("add3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key assignments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string assignment {
            get {
                return ResourceManager.GetString("assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Backward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter cue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cue {
            get {
                return ResourceManager.GetString("cue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   German に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit1 {
            get {
                return ResourceManager.GetString("Edit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string edit2 {
            get {
                return ResourceManager.GetString("edit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string endtime {
            get {
                return ResourceManager.GetString("endtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spanish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read subtitles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failed2 {
            get {
                return ResourceManager.GetString("failed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect item value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failed3 {
            get {
                return ResourceManager.GetString("failed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time values ​​out of sequence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failed4 {
            get {
                return ResourceManager.GetString("failed4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time must be earlier than end time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failed5 {
            get {
                return ResourceManager.GetString("failed5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtitle fix(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fix {
            get {
                return ResourceManager.GetString("fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix subtitles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fix2 {
            get {
                return ResourceManager.GetString("fix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   French に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language(&amp;L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load text in a new line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode(&amp;M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start→End→End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mode1 {
            get {
                return ResourceManager.GetString("mode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start→End→Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mode2 {
            get {
                return ResourceManager.GetString("mode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   disenable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OneLineModeDisEnable {
            get {
                return ResourceManager.GetString("OneLineModeDisEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OneLineModeEnable {
            get {
                return ResourceManager.GetString("OneLineModeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtitles already exist.
        ///Overwrite and save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string overwrite {
            get {
                return ResourceManager.GetString("overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount of start time rewind (ms) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rewind {
            get {
                return ResourceManager.GetString("rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Russian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your changes have not been saved, are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string save1 {
            get {
                return ResourceManager.GetString("save1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to seek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string seek {
            get {
                return ResourceManager.GetString("seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   amount to seek (ms) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string seek1 {
            get {
                return ResourceManager.GetString("seek1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string starttime {
            get {
                return ResourceManager.GetString("starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Subtitle(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtitle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string subtitle1 {
            get {
                return ResourceManager.GetString("subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtitle files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string subtitlefile {
            get {
                return ResourceManager.GetString("subtitlefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Happy Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing is written in the textbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string textboxerror {
            get {
                return ResourceManager.GetString("textboxerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open video(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video is not loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string videofailed {
            get {
                return ResourceManager.GetString("videofailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zh {
            get {
                return ResourceManager.GetString("zh", resourceCulture);
            }
        }
    }
}
